modLoader="javafml"
loaderVersion="[37,41)"
issueTrackerURL="https://github.com/glowstone314/MF3F/issues"
license="Unlicense"
[[mods]]
modId="mf3f"
version="3.0.0"
displayName="Mining Fatigue 3 Fix"
displayURL="https://github.com/glowstone314/MF3F"
logoFile="icon.png"
credits="Glow_Creeper"
authors="Glow_Creeper"
description='''Fix destroy speed multiplier for Mining Fatigue 3 and higher
修复挖掘疲劳3及更高的挖掘速度乘数'''
